name: BBGG
version: "2020.09.05"
license: "GPL-2.0-or-later"
date: 2020-09-05
description: |
    Beilinson monads and derived categories for coherent sheaves over P^n

authors:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh

maintainers:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "GradedModulePresentationsForCAP"
      version: ">= 0.1"
      url: "https://homalg-project.github.io/CAP_project/"
    - name: "GradedModules"
      version: ">= 2020.04.30"
      url: "https://homalg-project.github.io/homalg_project/GradedModules/"
    - name: "GradedRingForHomalg"
      version: ">= 2020.05.01"
      url: "https://homalg-project.github.io/homalg_project/GradedRingForHomalg/"
    - name: "Bicomplexes"
      version: ">= 2020.03.11"
      url: "https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/Bicomplexes"
    - name: "StableCategories"
      version: ">= 2019.12.04"
      url: "https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/StableCategories"
    - name: "LinearAlgebraForCAP"
      version: ">= 2020.04.16"
      url: "http://homalg-project.github.io/CAP_project/LinearAlgebraForCAP/"
    - name: "SubcategoriesForCAP"
      version: ">= 2020.04.05"
      url: "https://homalg-project.github.io/SubcategoriesForCAP"
    - name: "FreydCategoriesForCAP"
      version: ">= 2019.11.02"
      url: "https://github.com/homalg-project/CAP_project/tree/master/FreydCategoriesForCAP"

www: https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/BBGG
readme: README.md
packageinfo: https://raw.githubusercontent.com/homalg-project/HigherHomologicalAlgebra/master/BBGG/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/HigherHomologicalAlgebra/releases/download/BBGG-2020.09.05/BBGG-2020.09.05.tar.gz

abstract: |
    The <span class='pkgname'>BBGG</span> package provides a GAP package to implement the Bernstein, Gelfand and Gelfand correspondence, in order to give several models for the derived category of coherent sheaves, over the projective space. First as a triangulated stable category over left modules over exterior algebras and the secondly by constructing the Beilinson monads.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Beilinson monads, Tate resolutions, Derived categories, Projective space, Coherent sheaves.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Sal20</span>]   <b class='BibAuthor'>Saleh, K.</b>,
     <i class='BibTitle'>BBGG, Beilinson monads and derived categories for coherent sheaves over P^n,
             Version 2020.09.05</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/BBGG">https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/BBGG</a></span>.
    </p>
    

bibtex: |
    @misc{ BBGG2020.09.05,
      author =           {Saleh, K.},
      title =            {{BBGG}, Beilinson monads and derived categories for coherent sheaves over P\texttt{\symbol{94}}n, {V}ersion 2020.09.05},
      month =            {Sep},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href              {https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/BBGG}             {\texttt{https://github.com/}\discretionary
                          {}{}{}\texttt{homalg-project/}\discretionary          {}{}{}\texttt{HigherHomologicalAlgebra/}\discretionary          {}{}{}\texttt{tree/}\discretionary
                          {}{}{}\texttt{master/}\discretionary {}{}{}\texttt{BBGG}}},
      keywords =         {Beilinson monads; Tate resolutions; Derived categories; Projective space; Coherent sheaves},
      printedkey =       {Sal20}
    }

