markdown:    kramdown
highlighter: rouge

baseurl:     /HigherHomologicalAlgebra

include: ['BBGG', 'Bicomplexes', 'ComplexesCategories', 'DerivedCategories', 'HomotopyCategories', 'QuotientCategories', 'StableCategories', 'ToolsForHigherHomologicalAlgebra', 'TriangulatedCategories']
exclude: [ "index_default.template" ]

repository: homalg-project/HigherHomologicalAlgebra
