name: Bicomplexes
version: "2020.09.05"
license: "GPL-2.0-or-later"
date: 2020-09-05
description: |
    Bicomplexes for Abelian categories

authors:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "ComplexesCategories"
      version: ">= 2020.03.12"
      url: "https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/ComplexesCategories"

www: https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/Bicomplexes
readme: README.md
packageinfo: https://raw.githubusercontent.com/homalg-project/HigherHomologicalAlgebra/master/Bicomplexes/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/HigherHomologicalAlgebra/releases/download/Bicomplexes-2020.09.05/Bicomplexes-2020.09.05.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    bicomplexes, abelian category.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BS20</span>]   <b class='BibAuthor'>Barakat, M. and Saleh, K.</b>,
     <i class='BibTitle'>Bicomplexes, Bicomplexes for Abelian categories,
             Version 2020.09.05</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/Bicomplexes">https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/Bicomplexes</a></span>.
    </p>
    

bibtex: |
    @misc{ Bicomplexes2020.09.05,
      author =           {Barakat, M. and Saleh, K.},
      title =            {{Bicomplexes}, Bicomplexes for Abelian categories, {V}ersion 2020.09.05},
      month =            {Sep},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href          {https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/Bicomplexes}          {\texttt{https://github.com/}\discretionary
                          {}{}{}\texttt{homalg-project/}\discretionary          {}{}{}\texttt{HigherHomologicalAlgebra/}\discretionary          {}{}{}\texttt{tree/}\discretionary
                          {}{}{}\texttt{master/}\discretionary {}{}{}\texttt{Bicomplexes}}},
      keywords =         {bicomplexes; abelian category},
      printedkey =       {BS20}
    }

