name: ComplexesCategories
version: "2020.09.05"
license: "GPL-2.0-or-later"
date: 2020-09-05
description: |
    Category of (co)chain complexes of an additive category

authors:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

maintainers:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

GAP: ">= 4.8"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2019.09.04"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "CAP"
      version: ">= 2020.08.01"
      url: "https://homalg-project.github.io/CAP_project/CAP"
    - name: "MonoidalCategories"
      version: ">= 2019.08.10"
      url: "https://homalg-project.github.io/CAP_project/MonoidalCategories"

suggested-pkgs:
    - name: "GeneralizedMorphismsForCAP"
      version: ">= 2019.08.10"
      url: "http://homalg-project.github.io/CAP_project/GeneralizedMorphismsForCAP/"

www: https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/ComplexesCategories
readme: README.md
packageinfo: https://raw.githubusercontent.com/homalg-project/HigherHomologicalAlgebra/master/ComplexesCategories/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/HigherHomologicalAlgebra/releases/download/ComplexesCategories-2020.09.05/ComplexesCategories-2020.09.05.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Chains, Cochains, MappingCone, MappingCylinder, Homotopy.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Sal20</span>]   <b class='BibAuthor'>Saleh, K.</b>,
     <i class='BibTitle'>ComplexesCategories, Category of (co)chain complexes of an additive category,
             Version 2020.09.05</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/ComplexesCategories">https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/ComplexesCategories</a></span>.
    </p>
    

bibtex: |
    @misc{ ComplexesCategories2020.09.05,
      author =           {Saleh, K.},
      title =            {{ComplexesCategories}, Category of (co)chain complexes of an additive category, {V}ersion 2020.09.05},
      month =            {Sep},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href      {https://github.com/homalg-project/HigherHomologicalAlgebra/tree/master/ComplexesCategories}      {\texttt{https://github.com/}\discretionary
                          {}{}{}\texttt{homalg-project/}\discretionary          {}{}{}\texttt{HigherHomologicalAlgebra/}\discretionary          {}{}{}\texttt{tree/}\discretionary
                          {}{}{}\texttt{master/}\discretionary {}{}{}\texttt{ComplexesCategories}}},
      keywords =         {Chains; Cochains; MappingCone; MappingCylinder; Homotopy},
      printedkey =       {Sal20}
    }

